name: Deploy

on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy to staging VM
        runs-on: self-hosted
        permissions:
            contents: read
        timeout-minutes: 15

        steps:
            - name: Pull latest code
              run: |
                  cd ~/pei/pei-automotive-backend
                  git pull origin main

            - name: Regenerate .env
              env:
                  WEATHER_API_URL: ${{ secrets.WEATHER_API_URL }}
                  WEATHER_USER: ${{ secrets.WEATHER_USER }}
                  WEATHER_PASS: ${{ secrets.WEATHER_PASS }}
                  KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
                  KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
                  KC_DB_USERNAME: ${{ secrets.KC_DB_USERNAME }}
                  KC_DB_PASSWORD: ${{ secrets.KC_DB_PASSWORD }}
              run: |
                  cd ~/pei/pei-automotive-backend
                  chmod +x make_env.sh
                  ./make_env.sh

            - name: Redeploy containers
              run: |
                  cd ~/pei/pei-automotive-backend
                  docker compose up --build -d
