name: Test

on:
    push:
        branches: [main]
    pull_request:

jobs:
    test:
        runs-on: [self-hosted, test-runner]
        permissions:
            contents: read
        timeout-minutes: 15
        env:
            CI: "true"

        steps:
            - uses: actions/checkout@v4

            - name: Add production Ditto to /etc/hosts
              run: |
                  echo "10.255.38.67 tomastest.com" | sudo tee -a /etc/hosts
                  echo "[INFO] Added tomastest.com to /etc/hosts"
                  cat /etc/hosts | grep tomastest.com

            - name: Check if all C2E pods are up
              run: |
                  NOT_READY=$(kubectl get pods -n cloud2edge --no-headers 2>/dev/null | grep -vE 'Running|Completed' | wc -l)
                  [ "$NOT_READY" -eq 0 ] || (echo "$NOT_READY pods not ready" && exit 1)
                  sleep 2

            - name: Install/Update dependencies
              run: |
                  pip install -r requirements.txt
                  sleep 2

            - name: Generate .env file
              env:
                  WEATHER_API_URL: ${{ secrets.WEATHER_API_URL }}
                  WEATHER_USER: ${{ secrets.WEATHER_USER }}
                  WEATHER_PASS: ${{ secrets.WEATHER_PASS }}
                  KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
                  KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
                  KC_DB_USERNAME: ${{ secrets.KC_DB_USERNAME }}
                  KC_DB_PASSWORD: ${{ secrets.KC_DB_PASSWORD }}
              run: |
                  chmod +x make_env.sh
                  ./make_env.sh
                  sleep 2

            - name: Start services
              run: |
                  docker compose --build -d
                  sleep 10

            - name: Run tests
              run: |
                  pytest -v

            - name: Cleanup
              if: always()
              run: docker compose down -v
